backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/page/home.md"
        fields:
          - { label: "Hero Image", name: "heroImage", widget: "image" }
          - { label: "Notification", name: "notification", widget: "string" }
          - label: "Section1"
            name: "section1"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "markdown" }
              - { label: "Description2", name: "description2", widget: "text" }
          - label: "News"
            name: "news"
            widget: list
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Image", name: "image", widget: "image" }
          - label: "Articles"
            name: "articles"
            widget: list
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "ReadMoreLink", name: "readmore", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Image", name: "image", widget: "image" }
